// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get API key from environment variable or use hardcoded fallback
// To get your API key: Go to Supabase Dashboard > Settings > API > anon/public key
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xstummjwfcmoljnagmsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzdHVtbWp3ZmNtb2xqbmFnbXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4OTk2OTksImV4cCI6MjA3ODQ3NTY5OX0.FboGdQMflJnsdW2KSboSFCvrR2LgOy7daTj5Y524baU";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom fetch that ensures apikey header is always included
const customFetch = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  // Convert URL to string for checking
  const urlString = typeof url === 'string' ? url : url instanceof URL ? url.toString() : String(url);
  
  console.log('[Supabase Fetch] Request intercepted:', {
    url: urlString,
    method: options?.method || 'GET',
    timestamp: new Date().toISOString(),
  });
  
  // Only intercept Supabase API requests
  if (!urlString.includes('supabase.co')) {
    console.log('[Supabase Fetch] Not a Supabase URL, passing through');
    return fetch(url, options);
  }
  
  // Handle headers - convert to Headers object if needed
  const originalHeaders = options?.headers;
  console.log('[Supabase Fetch] Original headers:', originalHeaders);
  
  const headers = new Headers(originalHeaders);
  
  // Log existing headers
  const existingHeaders: Record<string, string> = {};
  headers.forEach((value, key) => {
    existingHeaders[key] = key === 'apikey' ? value.substring(0, 20) + '...' : value;
  });
  console.log('[Supabase Fetch] Existing headers:', existingHeaders);
  
  // ALWAYS set apikey header for Supabase requests
  const hadApikey = headers.has('apikey');
  headers.set('apikey', SUPABASE_PUBLISHABLE_KEY);
  console.log('[Supabase Fetch] apikey header:', {
    hadApikey,
    nowSet: headers.has('apikey'),
    keyPreview: SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...',
  });
  
  // Ensure Content-Type is set for POST/PUT/PATCH requests
  if (options?.method && ['POST', 'PUT', 'PATCH'].includes(options.method.toUpperCase())) {
    if (!headers.has('Content-Type')) {
      headers.set('Content-Type', 'application/json');
      console.log('[Supabase Fetch] Added Content-Type header');
    }
  }
  
  // Log all final headers (sanitized)
  const finalHeaders: Record<string, string> = {};
  headers.forEach((value, key) => {
    finalHeaders[key] = key === 'apikey' || key === 'authorization' 
      ? value.substring(0, 20) + '...' 
      : value;
  });
  console.log('[Supabase Fetch] Final headers being sent:', finalHeaders);
  
  // CRITICAL: Verify apikey is actually in headers
  const apikeyValue = headers.get('apikey');
  console.log('[Supabase Fetch] VERIFICATION - apikey header value:', {
    exists: !!apikeyValue,
    length: apikeyValue?.length,
    matchesExpected: apikeyValue === SUPABASE_PUBLISHABLE_KEY,
    preview: apikeyValue?.substring(0, 30) + '...',
  });
  
  // Also log the actual headers object structure
  console.log('[Supabase Fetch] Headers object type:', headers.constructor.name);
  console.log('[Supabase Fetch] Headers entries:', Array.from(headers.entries()).map(([k, v]) => [
    k, 
    k === 'apikey' || k === 'authorization' ? v.substring(0, 20) + '...' : v
  ]));
  
  // Convert Headers object to plain object for fetch (more reliable)
  const headersObj: Record<string, string> = {};
  headers.forEach((value, key) => {
    headersObj[key] = value;
  });
  
  console.log('[Supabase Fetch] Converting headers to plain object:', {
    keys: Object.keys(headersObj),
    hasApikey: 'apikey' in headersObj,
    apikeyPreview: headersObj['apikey']?.substring(0, 30) + '...',
    allKeys: Object.keys(headersObj).join(', '),
  });
  
  const fetchOptions: RequestInit = {
    ...options,
    headers: headersObj, // Use plain object instead of Headers instance
  };
  
  console.log('[Supabase Fetch] Final fetch options:', {
    method: fetchOptions.method,
    headersKeys: Object.keys(fetchOptions.headers as Record<string, string> || {}),
    url: urlString,
  });
  
  const response = await fetch(url, fetchOptions);
  
  console.log('[Supabase Fetch] Response received:', {
    status: response.status,
    statusText: response.statusText,
    url: urlString,
    ok: response.ok,
  });
  
  return response;
};

console.log('[Supabase Client] Initializing Supabase client:', {
  url: SUPABASE_URL,
  hasApiKey: !!SUPABASE_PUBLISHABLE_KEY,
  apiKeyPreview: SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...',
  usingCustomFetch: true,
});

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public',
  },
  global: {
    fetch: customFetch,
  },
});

console.log('[Supabase Client] Client initialized successfully');