// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get API key from environment variable or use hardcoded fallback
// To get your API key: Go to Supabase Dashboard > Settings > API > anon/public key
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xstummjwfcmoljnagmsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "sb_publishable_iiuSalo3LI_PtgrLgFx98A_Cqti4Vo1";

// Debug: Log which API key is being used
console.log('[Supabase Config] Environment check:', {
  hasEnvVar: !!import.meta.env.VITE_SUPABASE_ANON_KEY,
  envVarValue: import.meta.env.VITE_SUPABASE_ANON_KEY ? import.meta.env.VITE_SUPABASE_ANON_KEY.substring(0, 30) + '...' : 'NOT SET',
  usingFallback: !import.meta.env.VITE_SUPABASE_ANON_KEY,
  finalKeyPreview: SUPABASE_PUBLISHABLE_KEY.substring(0, 30) + '...',
  finalKeyLength: SUPABASE_PUBLISHABLE_KEY.length,
});

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom fetch that ensures apikey header is always included
const customFetch = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  // Convert URL to string for checking
  const urlString = typeof url === 'string' ? url : url instanceof URL ? url.toString() : String(url);
  
  console.log('[Supabase Fetch] Request intercepted:', {
    url: urlString,
    method: options?.method || 'GET',
    timestamp: new Date().toISOString(),
  });
  
  // Only intercept Supabase API requests
  if (!urlString.includes('supabase.co')) {
    console.log('[Supabase Fetch] Not a Supabase URL, passing through');
    return fetch(url, options);
  }
  
  // Handle headers - convert to Headers object if needed
  const originalHeaders = options?.headers;
  console.log('[Supabase Fetch] Original headers:', originalHeaders);
  
  const headers = new Headers(originalHeaders);
  
  // Log existing headers
  const existingHeaders: Record<string, string> = {};
  headers.forEach((value, key) => {
    existingHeaders[key] = key === 'apikey' ? value.substring(0, 20) + '...' : value;
  });
  console.log('[Supabase Fetch] Existing headers:', JSON.stringify(existingHeaders, null, 2));
  
  // ALWAYS set apikey header for Supabase requests
  const hadApikey = headers.has('apikey');
  headers.set('apikey', SUPABASE_PUBLISHABLE_KEY);
  console.log('[Supabase Fetch] apikey header:', {
    hadApikey,
    nowSet: headers.has('apikey'),
    keyPreview: SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...',
  });
  
  // Ensure Content-Type is set for POST/PUT/PATCH requests
  if (options?.method && ['POST', 'PUT', 'PATCH'].includes(options.method.toUpperCase())) {
    if (!headers.has('Content-Type')) {
      headers.set('Content-Type', 'application/json');
      console.log('[Supabase Fetch] Added Content-Type header');
    }
  }
  
  // Log all final headers (sanitized)
  const finalHeaders: Record<string, string> = {};
  headers.forEach((value, key) => {
    finalHeaders[key] = key === 'apikey' || key === 'authorization' 
      ? value.substring(0, 20) + '...' 
      : value;
  });
  console.log('[Supabase Fetch] Final headers being sent:', JSON.stringify(finalHeaders, null, 2));
  
  // CRITICAL: Verify apikey is actually in headers
  const apikeyValue = headers.get('apikey');
  console.log('[Supabase Fetch] VERIFICATION - apikey header value:', JSON.stringify({
    exists: !!apikeyValue,
    length: apikeyValue?.length,
    matchesExpected: apikeyValue === SUPABASE_PUBLISHABLE_KEY,
    preview: apikeyValue?.substring(0, 50) + '...',
    end: '...' + apikeyValue?.substring((apikeyValue?.length || 0) - 20),
    expectedPreview: SUPABASE_PUBLISHABLE_KEY.substring(0, 50) + '...',
    expectedEnd: '...' + SUPABASE_PUBLISHABLE_KEY.substring(SUPABASE_PUBLISHABLE_KEY.length - 20),
    fullMatch: apikeyValue === SUPABASE_PUBLISHABLE_KEY,
  }, null, 2));
  
  // Also log the actual headers object structure
  console.log('[Supabase Fetch] Headers object type:', headers.constructor.name);
  console.log('[Supabase Fetch] Headers entries:', Array.from(headers.entries()).map(([k, v]) => [
    k, 
    k === 'apikey' || k === 'authorization' ? v.substring(0, 20) + '...' : v
  ]));
  
  // Convert Headers object to plain object for fetch (more reliable)
  const headersObj: Record<string, string> = {};
  headers.forEach((value, key) => {
    headersObj[key] = value;
  });
  
  // Log the converted headers object with full details
  const headersObjForLog: Record<string, string> = {};
  Object.keys(headersObj).forEach(key => {
    headersObjForLog[key] = key === 'apikey' || key === 'authorization' 
      ? headersObj[key].substring(0, 30) + '...' 
      : headersObj[key];
  });
  
  console.log('[Supabase Fetch] Converting headers to plain object:', JSON.stringify({
    keys: Object.keys(headersObj),
    hasApikey: 'apikey' in headersObj,
    apikeyValue: headersObj['apikey'] ? headersObj['apikey'].substring(0, 50) + '...' : 'MISSING',
    apikeyLength: headersObj['apikey']?.length || 0,
    allKeys: Object.keys(headersObj).join(', '),
    headersPreview: headersObjForLog,
  }, null, 2));
  
  const fetchOptions: RequestInit = {
    ...options,
    headers: headersObj, // Use plain object instead of Headers instance
  };
  
  const finalHeadersForLog = fetchOptions.headers as Record<string, string> || {};
  const finalHeadersPreview: Record<string, string> = {};
  Object.keys(finalHeadersForLog).forEach(key => {
    finalHeadersPreview[key] = key === 'apikey' || key === 'authorization' 
      ? finalHeadersForLog[key].substring(0, 30) + '...' 
      : finalHeadersForLog[key];
  });
  
  console.log('[Supabase Fetch] Final fetch options:', JSON.stringify({
    method: fetchOptions.method,
    headersKeys: Object.keys(finalHeadersForLog),
    hasApikey: 'apikey' in finalHeadersForLog,
    apikeyValue: finalHeadersForLog['apikey'] ? finalHeadersForLog['apikey'].substring(0, 50) + '...' : 'MISSING',
    headersPreview: finalHeadersPreview,
    url: urlString,
  }, null, 2));
  
  const response = await fetch(url, fetchOptions);
  
  console.log('[Supabase Fetch] Response received:', {
    status: response.status,
    statusText: response.statusText,
    url: urlString,
    ok: response.ok,
  });
  
  return response;
};

console.log('[Supabase Client] Initializing Supabase client:', JSON.stringify({
  url: SUPABASE_URL,
  hasApiKey: !!SUPABASE_PUBLISHABLE_KEY,
  apiKeyLength: SUPABASE_PUBLISHABLE_KEY.length,
  apiKeyPreview: SUPABASE_PUBLISHABLE_KEY.substring(0, 50) + '...',
  apiKeyEnd: '...' + SUPABASE_PUBLISHABLE_KEY.substring(SUPABASE_PUBLISHABLE_KEY.length - 20),
  usingCustomFetch: true,
}, null, 2));

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public',
  },
  global: {
    fetch: customFetch,
  },
});

console.log('[Supabase Client] Client initialized successfully');