// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get API key from environment variable or use hardcoded fallback
// To get your API key: Go to Supabase Dashboard > Settings > API > anon/public key
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xstummjwfcmoljnagmsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzdHVtbWp3ZmNtb2xqbmFnbXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4OTk2OTksImV4cCI6MjA3ODQ3NTY5OX0.FboGdQMflJnsdW2KSboSFCvrR2LgOy7daTj5Y524baU";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom fetch that ensures apikey header is always included
const customFetch = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const headers = new Headers(options?.headers);
  
  // Ensure apikey header is always present
  if (!headers.has('apikey')) {
    headers.set('apikey', SUPABASE_PUBLISHABLE_KEY);
  }
  
  // Ensure Content-Type is set for POST/PUT/PATCH requests
  if (options?.method && ['POST', 'PUT', 'PATCH'].includes(options.method.toUpperCase())) {
    if (!headers.has('Content-Type')) {
      headers.set('Content-Type', 'application/json');
    }
  }
  
  return fetch(url, {
    ...options,
    headers,
  });
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public',
  },
  global: {
    fetch: customFetch,
  },
});